version: "3.8"

services:
  inference:
    build: .
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["/data/public_test.csv", "/data/submission.csv"]
